### PR TITLE
issue #205 bugfix

### PR DESCRIPTION
**Pull request by MaciejKarasek**
Added if statements to check if value of attribute is not None. Function `hasattr` returns True when atrribute exists even if its value is None.

Related to issue #205

### CODE REVIEW

**Comment by NanoCode012** [comment]
Hello, thanks for the PR!

I'm curious on the effect of `hasattr(config, "max_seq_len")`. Would it work without this since we're performing the check you have newly added?

**Comment by MaciejKarasek** [comment]
> I'm curious on the effect of `hasattr(config, "max_seq_len")`. Would it work without this since we're performing the check you have newly added?

It would work if we are sure that attribute like max_seq_len is always a part of the config class. In case there is no attribute like that and if statement would look like this `if config.max_seq_len:` there's gonna be an error `AttributeError: type object 'config' has no attribute 'max_seq_len'`

**Comment by NanoCode012** [comment]
Ah, I made the mistake. Thank you for clarifying. I confused `config` with `cfg`. I thought they were the same.

**Comment by MaciejKarasek** [comment]
Seems I forgot to install pre-commit, but i think it not gonna work on mine python 3.11 cause in .pre-commit-config.yaml there is line `python: python3.9` so anyway :/

**Comment by NanoCode012** [comment]
Hey @MaciejKarasek , no worries. Actually, my python (for local dev) is also 3.11, so it might work as well :)

However, if you do not want to install, that's fine also! Feel free to look at the CI Details, and it would show you the issue and maybe a potential fix.

**Review by winglian — APPROVED** [review]
thank you! lmk if you need any help with the pre-commit hooks

**Comment by MaciejKarasek** [comment]
Thanks guys

**Comment by MaciejKarasek** [comment]
Should be all right now.
